# Generated by Django 5.2.5 on 2025-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('game_development', 'Game Development'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('requirements', models.TextField(help_text='Required skills and technologies')),
                ('duration', models.CharField(help_text='Expected project duration', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.CharField(help_text='Project supervisor name', max_length=255)),
                ('max_students', models.IntegerField(default=1, help_text='Maximum number of students')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
